import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
import "./final-refinement.css";
import "./precision-panels.css";
import "./season-lens.css";
import "./solar-ledger.css";
import "./nature-glass.css";
import "./layout-repair.css";
import "./culture-guide.css";
import "./mobile-optimizations.css";
import "./experience-enhancements.css";
import "./season-fieldbook.css";
import "./seasonal-visual-refinement.css";
import "./precision-polish.css";
import "./timeline-centring-fix.css";
import "./guide-reading-path.css";
import "./index-five-routes.css";
import "./season-place-shortcuts.css";

createRoot(document.getElementById("root")!).render(<App />);
