/** Glass Almanac reminder: discovery is a dedicated, calm search experience with low visual noise and direct access to each festival story. */
import { calendarRecords, kindColor, years, type Country, type FestivalRecord, type Kind } from "@/data/calendar";
import { ArrowRight, CalendarDays, Search, SlidersHorizontal, X } from "lucide-react";
import { Link } from "wouter";
import { useMemo, useState } from "react";
import { useLocale } from "@/contexts/LocaleContext";
import { kindLabels, shortDate, statusLabels } from "@/lib/festival";

const words = { id: { eyebrow: "Temukan perayaan", title: "Cari sedikit. Temukan banyak.", intro: "Gunakan kata, negara, jenis tradisi, atau tahun untuk menelusuri catatan kalender dengan lebih tenang.", placeholder: "Coba “Diwali”, “Agustus”, atau “Indonesia”", filters: "Saring", all: "Semua", india: "India", indonesia: "Indonesia", allKinds: "Semua tradisi", noResults: "Belum ada catatan yang cocok.", noResultsBody: "Coba kata yang lebih pendek atau hapus satu filter.", read: "Buka cerita", result: "catatan ditemukan", year: "Tahun" }, en: { eyebrow: "Find a celebration", title: "Search lightly. Discover deeply.", intro: "Use a word, country, tradition, or year to explore calendar notes with more calm.", placeholder: "Try “Diwali”, “August”, or “Indonesia”", filters: "Filters", all: "All", india: "India", indonesia: "Indonesia", allKinds: "All traditions", noResults: "No matching notes yet.", noResultsBody: "Try a shorter word or clear one filter.", read: "Open story", result: "notes found", year: "Year" } };
type CountryFilter = "All" | Country; type KindFilter = "All" | Kind;

export default function Explore() { const { language } = useLocale(); const t = words[language]; const [query,setQuery] = useState(""); const [country,setCountry] = useState<CountryFilter>("All"); const [kind,setKind] = useState<KindFilter>("All"); const [year,setYear] = useState(2026); const [filtersOpen,setFiltersOpen] = useState(false);
  const results = useMemo(() => calendarRecords.filter((record) => record.date.startsWith(String(year)) && (country === "All" || record.country === country) && (kind === "All" || record.kind === kind) && [record.title.en,record.title.id,record.country,record.kind].join(" ").toLowerCase().includes(query.toLowerCase())).sort((a,b) => a.date.localeCompare(b.date)), [country,kind,query,year]);
  const groups = useMemo(() => Array.from(results.reduce((map, record) => { const key = record.date.slice(5,7); const value = map.get(key) || []; value.push(record); map.set(key, value); return map; }, new Map<string, FestivalRecord[]>()).entries()), [results]);
  const reset = () => { setQuery(""); setCountry("All"); setKind("All"); };
  return <section className="explore-page"><header className="explore-heading"><span className="eyebrow"><Search size={14}/>{t.eyebrow}</span><h1>{t.title}</h1><p>{t.intro}</p></header><div className="discover-console"><div className="search-console"><Search size={21}/><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.placeholder}/>{query && <button onClick={() => setQuery("")} aria-label="Clear search"><X size={16}/></button>}</div><button className="filter-trigger" onClick={() => setFiltersOpen((value)=>!value)}><SlidersHorizontal size={17}/>{t.filters}</button></div><div className={`filter-sheet ${filtersOpen ? "open" : ""}`}><div className="filter-group"><span>{t.year}</span><div>{years.map((item) => <button key={item} onClick={() => setYear(item)} className={year === item ? "active" : ""}>{item}</button>)}</div></div><div className="filter-group"><span>{t.filters}</span><div>{(["All","India","Indonesia"] as CountryFilter[]).map((item) => <button key={item} onClick={() => setCountry(item)} className={country === item ? "active" : ""}>{item === "All" ? t.all : item === "India" ? t.india : t.indonesia}</button>)}</div></div><div className="filter-group"><span>{t.allKinds}</span><div>{(["All","National","Hindu","Islamic","Sikh","Christian","Buddhist","Jain","Confucian","Cultural","Special"] as KindFilter[]).map((item) => <button key={item} onClick={() => setKind(item)} className={kind === item ? "active" : ""}>{item === "All" ? t.allKinds : kindLabels[language][item]}</button>)}</div></div><button className="clear-filters" onClick={reset}>Reset</button></div><div className="result-head"><span>{results.length} {t.result}</span><span>{year}</span></div><div className="result-list">{results.length ? groups.map(([month, entries]) => <section className="month-ledger" key={month}><header><span>{month}</span><div><strong>{new Intl.DateTimeFormat(language === "id" ? "id-ID" : "en-GB", { month:"long", timeZone:"UTC" }).format(new Date(`${year}-${month}-01T12:00:00Z`))}</strong><small>{entries.length} {t.result}</small></div></header>{entries.map((record) => <Link href={`/festival/${record.id}`} key={record.id} className="festival-row"><time><strong>{record.date.slice(8)}</strong><span>{new Intl.DateTimeFormat(language === "id" ? "id-ID" : "en-GB", { month:"short", timeZone:"UTC" }).format(new Date(`${record.date}T12:00:00Z`))}</span></time><span className={`result-dot ${kindColor[record.kind]}`}/><div><span className="small-meta">{record.country} · {kindLabels[language][record.kind]}</span><h3>{record.title[language]}</h3></div><span className={`status-chip ${record.status}`}>{statusLabels[language][record.status]}</span><ArrowRight size={17}/></Link>)}</section>) : <div className="empty-search"><CalendarDays size={26}/><h3>{t.noResults}</h3><p>{t.noResultsBody}</p><button onClick={reset}>Reset</button></div>}</div></section>; }
