/** Glass Almanac reminder: festival stories are calm, direct and culturally careful, with one clear exit and readable blocks. */
import { calendarRecords, kindColor } from "@/data/calendar";
import { ArrowLeft, ArrowRight, CalendarDays, CircleCheck, MapPin, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";
import { useLocale } from "@/contexts/LocaleContext";
import { casualDescription, dayRhythm, fieldNote, kindLabels, longDate, statusLabels } from "@/lib/festival";

const words = { id: { back: "Kembali ke jelajah", today: "Sekilas tentang hari ini", happens: "Yang biasanya terjadi", good: "Baik untuk diketahui", goodBody: "Cara merayakan dapat berbeda menurut wilayah, keluarga, komunitas, dan kalender setempat. Gunakan catatan ini sebagai pintu masuk, lalu cek pengumuman lokal jika kamu membuat rencana.", next: "Catatan berikutnya", status: "Status tanggal" }, en: { back: "Back to explore", today: "The day at a glance", happens: "What people often do", good: "Good to know", goodBody: "Practice can differ across regions, families, communities, and local calendars. Use this note as a starting point, then check local announcements when making plans.", next: "Next note", status: "Date status" } };

export default function FestivalDetail() { const [, params] = useRoute("/festival/:id"); const { language } = useLocale(); const t = words[language]; const record = calendarRecords.find((item) => item.id === params?.id); if (!record) return <section className="detail-page missing"><Link href="/explore"><ArrowLeft size={16}/>{t.back}</Link><h1>Festival not found</h1></section>; const index = calendarRecords.findIndex((item) => item.id === record.id); const next = calendarRecords.slice(index + 1).find((item) => item.country === record.country) || calendarRecords[0]; return <section className="detail-page"><Link href="/explore" className="back-link"><ArrowLeft size={16}/>{t.back}</Link><header className="detail-hero"><span className={`detail-orbit ${kindColor[record.kind]}`}>{record.kind.slice(0,1)}</span><div><span className="eyebrow"><MapPin size={14}/>{record.country} · {kindLabels[language][record.kind]}</span><h1>{record.title[language]}</h1><p>{longDate(record.date, language)}</p></div><span className={`status-chip ${record.status}`}>{statusLabels[language][record.status]}</span></header><div className="detail-field-strip"><span>FIELD NOTE · {record.date.slice(0,4)}</span><p>{fieldNote(record, language)}</p><div className={`festival-material ${kindColor[record.kind]}`}><i/><i/><i/><b/></div></div><div className="story-grid"><article><span className="eyebrow"><Sparkles size={14}/>{t.today}</span><h2>{casualDescription(record, language)}</h2></article><article><span className="eyebrow"><CalendarDays size={14}/>{t.happens}</span><p>{dayRhythm(record, language)}</p></article><article><span className="eyebrow"><CircleCheck size={14}/>{t.good}</span><p>{t.goodBody}</p><div className="status-explainer"><span>{t.status}</span><strong>{statusLabels[language][record.status]}</strong></div></article></div><Link href={`/festival/${next.id}`} className="next-detail"><span>{t.next}</span><strong>{next.title[language]}</strong><ArrowRight size={17}/></Link></section>; }
