/** Glass Almanac reminder: the home view answers “what is happening today?” quickly, with generous whitespace and a small companion rather than visual clutter. */
import { calendarRecords, kindColor, type Country } from "@/data/calendar";
import { Bell, BellOff, CalendarDays, ChevronRight, Clock3, MapPin, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { useEffect, useMemo, useState } from "react";
import { useLocale } from "@/contexts/LocaleContext";
import { casualDescription, kindLabels, longDate, statusLabels, zonedDate } from "@/lib/festival";

type CountryFilter = "All" | Country;
const words = { id: { eyebrow: "Pendamping hari ini", title: "Kecil di layar. Besar dalam makna.", intro: "Temukan perayaan, hari penting, dan ritme budaya India serta Indonesia—tanpa harus menelusuri kalender yang rumit.", explore: "Jelajahi kalender", date: "Pilih tanggal", today: "Hari ini", clock: "Jam lokal", noTitle: "Tidak ada perayaan terjadwal hari ini.", noBody: "Hari ini tenang di kalender pilihanmu. Pilih tanggal lain atau lihat perayaan terdekat.", onToday: "Sedang berlangsung hari ini", read: "Baca kisahnya", all: "Semua", india: "India", indonesia: "Indonesia", reminderTitle: "Pengingat, saat kamu membutuhkannya.", reminderBody: "Aktifkan untuk melihat pengingat ketika aplikasi terbuka atau kembali aktif di hari perayaan.", enable: "Aktifkan", disable: "Matikan", notificationsBlocked: "Izin notifikasi diblokir di browser ini.", next: "Berikutnya" }, en: { eyebrow: "Today’s companion", title: "Small on screen. Big in meaning.", intro: "Discover celebrations, special days, and the cultural rhythms of India and Indonesia—without untangling a complicated calendar.", explore: "Explore the calendar", date: "Choose a date", today: "Today", clock: "Local time", noTitle: "No celebration is scheduled today.", noBody: "Your selected calendar is quiet today. Pick another date or see the next celebration.", onToday: "Happening today", read: "Read the story", all: "All", india: "India", indonesia: "Indonesia", reminderTitle: "Reminders, when you need them.", reminderBody: "Enable a reminder when the app is open or resumes on a celebration day.", enable: "Enable", disable: "Turn off", notificationsBlocked: "Notifications are blocked in this browser.", next: "Next up" } };

const clocks = [{ label: "IST", zone: "Asia/Kolkata" }, { label: "WIB", zone: "Asia/Jakarta" }, { label: "WITA", zone: "Asia/Makassar" }, { label: "WIT", zone: "Asia/Jayapura" }];
function Clock({ label, zone }: { label: string; zone: string }) { const [now, setNow] = useState(new Date()); useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(timer); }, []); return <div className="tiny-clock"><span>{label}</span><strong>{new Intl.DateTimeFormat("en-GB", { timeZone: zone, hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(now)}</strong></div>; }
function Mika({ festive }: { festive: boolean }) { return <div className={`mika-mini ${festive ? "festive" : ""}`} aria-label="Mika"><i className="mika-ear one"/><i className="mika-ear two"/><i className="mika-eye one"/><i className="mika-eye two"/><i className="mika-nose"/></div>; }

export default function Home() {
  const { language } = useLocale(); const t = words[language];
  const [country, setCountry] = useState<CountryFilter>("All"); const [selectedDate, setSelectedDate] = useState(() => zonedDate("Asia/Jakarta")); const [reminders, setReminders] = useState(() => localStorage.getItem("ka-reminders") === "true"); const [permission, setPermission] = useState<NotificationPermission | "unsupported">(() => "Notification" in window ? Notification.permission : "unsupported");
  const today = zonedDate("Asia/Jakarta"); const records = useMemo(() => calendarRecords.filter((entry) => entry.date === selectedDate && (country === "All" || entry.country === country)), [country, selectedDate]); const next = useMemo(() => calendarRecords.filter((entry) => entry.date > selectedDate && (country === "All" || entry.country === country)).sort((a,b) => a.date.localeCompare(b.date))[0], [country, selectedDate]);
  const toggleReminder = async () => { if (reminders) { localStorage.setItem("ka-reminders","false"); setReminders(false); return; } if (!("Notification" in window)) { setPermission("unsupported"); return; } const result = await Notification.requestPermission(); setPermission(result); if (result === "granted") { localStorage.setItem("ka-reminders","true"); setReminders(true); } };
  return <>
    <section className="home-hero"><div className="hero-copy-new"><span className="eyebrow"><Sparkles size={14}/>{t.eyebrow}</span><h1>{t.title}</h1><p>{t.intro}</p><div className="home-actions"><Link href="/explore" className="primary-action"><CalendarDays size={17}/>{t.explore}</Link><label className="date-control"><span>{t.date}</span><input type="date" min="2026-01-01" max="2030-12-31" value={selectedDate} onChange={(event) => setSelectedDate(event.target.value)}/></label></div></div><div className="hero-calendar-object" aria-hidden="true"><div className="object-route"><span>INDIA</span><i/><span>INDONESIA</span></div><div className="object-stamp">FIELD<br/>ATLAS</div><div className="object-line one"/><div className="object-line two"/><div className="object-card"><span>KA · AUG 2026</span><i/><i/><i/></div><div className="object-textile"><i/><i/><i/><i/></div><div className="object-lamp"/><div className="object-flower"><i/><i/><i/><i/><b/></div></div></section>
    <section className="today-wrap"><aside className="clock-card"><span className="eyebrow"><Clock3 size={14}/>{t.clock}</span><div className="clock-row">{clocks.map((item) => <Clock key={item.label} {...item}/>)}</div></aside><div className="today-main"><div className="today-topline"><div><span className="eyebrow"><MapPin size={14}/>{selectedDate === today ? t.today : longDate(selectedDate, language)}</span><h2>{longDate(selectedDate, language)}</h2></div><div className="country-pills">{(["All","India","Indonesia"] as CountryFilter[]).map((item) => <button key={item} onClick={() => setCountry(item)} className={country === item ? "active" : ""}>{item === "All" ? t.all : item === "India" ? t.india : t.indonesia}</button>)}</div></div><div className="today-panel">{records.length ? <div className="today-records"><span className="eyebrow accent">{t.onToday}</span>{records.map((record) => <Link href={`/festival/${record.id}`} className="today-story" key={record.id}><span className={`story-token ${kindColor[record.kind]}`}>{record.kind.slice(0,1)}</span><div><span className="small-meta">{record.country} · {kindLabels[language][record.kind]}</span><h3>{record.title[language]}</h3><p>{casualDescription(record, language)}</p><span className="story-link">{t.read}<ChevronRight size={15}/></span></div><span className={`status-chip ${record.status}`}>{statusLabels[language][record.status]}</span></Link>)}</div> : <div className="quiet-state"><Mika festive={false}/><div><span className="eyebrow accent">{t.today}</span><h3>{t.noTitle}</h3><p>{t.noBody}</p>{next && <Link href={`/festival/${next.id}`} className="next-story"><span>{t.next}</span><strong>{next.title[language]}</strong><ChevronRight size={15}/></Link>}</div></div>}<Mika festive={records.length > 0}/></div></div></section>
    <section className="home-bottom"><article className="reminder-card"><span className="eyebrow"><Bell size={14}/>{t.reminderTitle}</span><p>{permission === "denied" ? t.notificationsBlocked : t.reminderBody}</p><button onClick={toggleReminder} className={reminders ? "reminder-button on" : "reminder-button"}>{reminders ? <BellOff size={16}/> : <Bell size={16}/>} {reminders ? t.disable : t.enable}</button></article><Link href="/guide" className="guide-teaser"><span className="eyebrow">KA Festivals</span><h3>{language === "id" ? "Kalender yang jelas, tanpa asumsi." : "A clear calendar, without assumptions."}</h3><span>{language === "id" ? "Cara membaca tanggal" : "How to read dates"}<ChevronRight size={16}/></span></Link></section>
  </>;
}
