/** KA Festivals: a bilingual daily companion with a calm field-journal interface, timezone-aware clocks, and a tiny CSS-drawn cat. */
import { calendarRecords, kindColor, type Country, type FestivalRecord, type Kind, type Locale } from "@/data/calendar";
import { Bell, BellOff, CalendarCheck2, Cat, Check, ChevronDown, Clock3, Download, Globe2, Info, Languages, MapPin, Search, Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type InstallPromptEvent = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> };
type CountryFilter = "All" | Country;

const copy = {
  id: { navDaily: "Hari ini", navCalendar: "Kalender", navGuide: "Panduan", install: "Pasang aplikasi", dailyKicker: "Pendamping hari ini", heading: "Rayakan hari ini, dengan konteks yang hangat.", intro: "KA Festivals menunjukkan perayaan yang berlangsung hari ini di India dan Indonesia—dengan bahasa yang santai, jelas, dan mudah dibaca.", dateLabel: "Pilih tanggal", countryLabel: "Wilayah", allCountries: "Semua negara", india: "India", indonesia: "Indonesia", today: "Hari ini", noFestival: "Tidak ada festival terjadwal hari ini.", noFestivalDesc: "Hari ini tenang di kalender pilihanmu. Mika menyarankan untuk melihat perayaan berikutnya.", festivalToday: "Ada perayaan hari ini", casualNote: "Apa yang biasanya terjadi?", clockTitle: "Jam lokal sekarang", yearKicker: "Kalender 2026–2030", yearHeading: "Jelajahi lima tahun, satu hari dalam satu waktu.", yearNote: "Tanggal resmi dan perkiraan ditandai agar kamu tahu mana yang perlu dicek ulang.", verified: "Terverifikasi", estimate: "Perkiraan", review: "Menunggu pengumuman resmi", sourceNote: "Tanggal lunar, Hijriah, Saka, Pawukon, dan hari libur pemerintah bisa berubah. Selalu cek pengumuman lokal sebelum membuat rencana.", searchPlaceholder: "Cari festival atau hari penting", result: "catatan kalender", todayShortcut: "Kembali ke hari ini", notificationTitle: "Pengingat festival", enableNotifications: "Aktifkan pengingat", disableNotifications: "Matikan pengingat", notificationReady: "Pengingat aktif saat aplikasi dibuka atau kembali aktif.", notificationBlocked: "Notifikasi diblokir di browser. Ubah izin situs untuk mengaktifkannya.", notificationUnsupported: "Browser ini belum mendukung notifikasi.", notificationCaveat: "Versi statis ini tidak dapat menjamin notifikasi saat browser benar-benar tertutup. Saat aplikasi terbuka atau dibuka kembali di hari festival, pengingat akan muncul.", pwaInstalled: "Aplikasi sudah terpasang", pwaReady: "Pasang KA Festivals untuk akses cepat dan tampilan seperti aplikasi.", language: "Bahasa", loadMore: "Tampilkan lebih banyak", futureIndo: "Tanggal hari libur keagamaan Indonesia untuk tahun ini menunggu keputusan resmi. Hari tetap dan hari budaya tetap ditampilkan.", metadata: "Kalender budaya India dan Indonesia, hari penting, zona waktu, dan pengingat festival." },
  en: { navDaily: "Today", navCalendar: "Calendar", navGuide: "Guide", install: "Install app", dailyKicker: "Today’s companion", heading: "Celebrate today, with gentle context.", intro: "KA Festivals shows what is happening today in India and Indonesia—using warm, clear, everyday language.", dateLabel: "Choose a date", countryLabel: "Region", allCountries: "Both countries", india: "India", indonesia: "Indonesia", today: "Today", noFestival: "No festival is scheduled today.", noFestivalDesc: "Today is quiet in your selected calendar. Mika suggests checking the next celebration.", festivalToday: "There is a celebration today", casualNote: "What usually happens?", clockTitle: "Local time now", yearKicker: "Calendar 2026–2030", yearHeading: "Explore five years, one day at a time.", yearNote: "Official and estimated dates are marked so you know what needs a local check.", verified: "Verified", estimate: "Estimated", review: "Awaiting official announcement", sourceNote: "Lunar, Hijri, Saka, Pawukon and government dates can move. Always confirm local announcements before making plans.", searchPlaceholder: "Search a festival or special day", result: "calendar notes", todayShortcut: "Return to today", notificationTitle: "Festival reminders", enableNotifications: "Enable reminders", disableNotifications: "Turn reminders off", notificationReady: "Reminders are active while the app is open or resumes.", notificationBlocked: "Notifications are blocked in this browser. Change this site’s permission to turn them on.", notificationUnsupported: "This browser does not support notifications.", notificationCaveat: "A static website cannot guarantee alerts while the browser is fully closed. When the app is open or resumed on a festival day, a reminder will appear.", pwaInstalled: "App installed", pwaReady: "Install KA Festivals for quick, app-like access.", language: "Language", loadMore: "Show more", futureIndo: "Indonesia’s official religious public-holiday dates for this year are awaiting government announcement. Fixed and cultural dates remain available.", metadata: "An India and Indonesia cultural calendar with special days, time zones and festival reminders." }
} as const;

const zoneList = [{ label: "India · IST", zone: "Asia/Kolkata", country: "India" }, { label: "Indonesia · WIB", zone: "Asia/Jakarta", country: "Indonesia" }, { label: "Indonesia · WITA", zone: "Asia/Makassar", country: "Indonesia" }, { label: "Indonesia · WIT", zone: "Asia/Jayapura", country: "Indonesia" }];
const kindLabels: Record<Locale, Record<Kind, string>> = { id: { National: "Nasional", Hindu: "Hindu", Islamic: "Islam", Sikh: "Sikh", Christian: "Kristen", Buddhist: "Buddha", Jain: "Jain", Confucian: "Konghucu", Cultural: "Budaya", Special: "Hari penting" }, en: { National: "National", Hindu: "Hindu", Islamic: "Islamic", Sikh: "Sikh", Christian: "Christian", Buddhist: "Buddhist", Jain: "Jain", Confucian: "Confucian", Cultural: "Cultural", Special: "Special day" } };

function zonedDate(timeZone: string) {
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date());
  const get = (type: string) => parts.find((item) => item.type === type)?.value || "";
  return `${get("year")}-${get("month")}-${get("day")}`;
}

function longDate(value: string, language: Locale, timeZone = "Asia/Jakarta") {
  return new Intl.DateTimeFormat(language === "id" ? "id-ID" : "en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric", timeZone }).format(new Date(`${value}T12:00:00Z`));
}

function Clock({ label, zone }: { label: string; zone: string }) {
  const [now, setNow] = useState(() => new Date());
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(timer); }, []);
  return <div className="zone-clock"><span>{label}</span><strong>{new Intl.DateTimeFormat("en-GB", { timeZone: zone, hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23" }).format(now)}</strong></div>;
}

function CatCompanion({ hasFestival, language }: { hasFestival: boolean; language: Locale }) {
  return <div className={`mika ${hasFestival ? "celebrating" : "resting"}`} aria-label="Mika, the KA Festivals cat companion"><div className="cat-tail" /><div className="cat-body" /><div className="cat-head"><i className="ear left" /><i className="ear right" /><i className="eye left" /><i className="eye right" /><i className="nose" /></div><div className="mika-copy"><Cat size={15} /><span>{hasFestival ? (language === "id" ? "Mika sedang ikut merayakan." : "Mika is joining the celebration.") : (language === "id" ? "Mika menikmati hari yang tenang." : "Mika is enjoying a quiet day.")}</span></div></div>;
}

function casualDescription(record: FestivalRecord, language: Locale) {
  const templates = {
    id: { National: "Hari penting ini biasanya diisi dengan upacara, cerita sejarah, dan kegiatan bersama di banyak tempat.", Hindu: "Biasanya ada doa, dekorasi, makanan khas, dan waktu bersama keluarga atau komunitas.", Islamic: "Banyak orang berkumpul untuk berdoa, berbagi makanan, dan saling mengunjungi dengan hangat.", Sikh: "Perayaan ini sering diisi dengan kunjungan ke gurdwara, musik rohani, dan kegiatan berbagi.", Christian: "Komunitas biasanya berkumpul untuk ibadah, refleksi, musik, dan waktu bersama keluarga.", Buddhist: "Hari ini sering diisi dengan meditasi, kunjungan ke vihara, dan tindakan kebaikan.", Jain: "Perayaan ini mengajak refleksi, doa, dan praktik welas asih atau tanpa kekerasan.", Confucian: "Keluarga, makanan bersama, doa, dan harapan baik menjadi bagian penting dari hari ini.", Cultural: "Ini adalah momen budaya yang sering hadir lewat seni, makanan, tradisi lokal, dan kebersamaan.", Special: "Hari ini menjadi kesempatan untuk belajar, menghargai tokoh penting, dan mengikuti kegiatan komunitas." },
    en: { National: "This day is often marked with ceremonies, history, and shared community activities.", Hindu: "People often gather for prayer, decorations, special food, and time with family or community.", Islamic: "Many people gather to pray, share food, and visit one another with warmth.", Sikh: "The day often includes gurdwara visits, devotional music, and acts of sharing.", Christian: "Communities commonly gather for worship, reflection, music, and family time.", Buddhist: "The day is often observed with meditation, temple visits, and acts of kindness.", Jain: "This observance invites reflection, prayer, and practices of compassion or non-violence.", Confucian: "Family, shared food, prayer, and good wishes are central to the day.", Cultural: "This cultural moment often comes alive through art, food, local tradition, and togetherness.", Special: "It is a chance to learn, appreciate an important figure, and join community activity." }
  } as const;
  return templates[language][record.kind];
}

function statusLabel(status: FestivalRecord["status"], language: Locale) { return copy[language][status]; }

export default function Home() {
  const [language, setLanguage] = useState<Locale>(() => (localStorage.getItem("ka-locale") as Locale) || "id");
  const [country, setCountry] = useState<CountryFilter>("All");
  const [selectedDate, setSelectedDate] = useState(() => zonedDate("Asia/Jakarta"));
  const [query, setQuery] = useState("");
  const [limit, setLimit] = useState(18);
  const [installPrompt, setInstallPrompt] = useState<InstallPromptEvent | null>(null);
  const [installed, setInstalled] = useState(false);
  const [reminders, setReminders] = useState(() => localStorage.getItem("ka-reminders") === "true");
  const [notificationState, setNotificationState] = useState<NotificationPermission | "unsupported">(() => "Notification" in window ? Notification.permission : "unsupported");
  const t = copy[language];
  const year = Number(selectedDate.slice(0, 4));

  useEffect(() => { localStorage.setItem("ka-locale", language); document.documentElement.lang = language; document.title = language === "id" ? "KA Festivals — Kalender Perayaan India & Indonesia" : "KA Festivals — India & Indonesia Festival Calendar"; const meta = document.querySelector('meta[name="description"]'); if (meta) meta.setAttribute("content", t.metadata); }, [language, t.metadata]);
  useEffect(() => { if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => undefined); const handler = (event: Event) => { event.preventDefault(); setInstallPrompt(event as InstallPromptEvent); }; window.addEventListener("beforeinstallprompt", handler); window.addEventListener("appinstalled", () => { setInstalled(true); setInstallPrompt(null); }); return () => window.removeEventListener("beforeinstallprompt", handler); }, []);

  const dayRecords = useMemo(() => calendarRecords.filter((entry) => entry.date === selectedDate && (country === "All" || entry.country === country)), [selectedDate, country]);
  const calendarResults = useMemo(() => calendarRecords.filter((entry) => entry.date.slice(0, 4) === String(year) && (country === "All" || entry.country === country) && [entry.title.en, entry.title.id, entry.kind, entry.country].join(" ").toLowerCase().includes(query.trim().toLowerCase())).sort((a, b) => a.date.localeCompare(b.date)), [country, query, year]);
  const isToday = selectedDate === zonedDate("Asia/Jakarta");

  useEffect(() => {
    if (!reminders || notificationState !== "granted") return;
    const notify = async () => {
      const indiaToday = zonedDate("Asia/Kolkata"); const indonesiaToday = zonedDate("Asia/Jakarta");
      const matches = calendarRecords.filter((entry) => (entry.country === "India" ? entry.date === indiaToday : entry.date === indonesiaToday) && entry.status !== "review");
      for (const entry of matches.slice(0, 2)) { const key = `ka-notified-${entry.id}`; if (localStorage.getItem(key)) continue; const title = language === "id" ? `${entry.title.id} hari ini` : `${entry.title.en} today`; try { if (navigator.serviceWorker?.controller) { const registration = await navigator.serviceWorker.ready; await registration.showNotification(title, { body: casualDescription(entry, language), icon: "/icon.svg", tag: entry.id }); } else { new Notification(title, { body: casualDescription(entry, language), icon: "/icon.svg" }); } localStorage.setItem(key, "yes"); } catch { /* browser permission or platform policy handles this */ } }
    };
    notify(); const timer = window.setInterval(notify, 60_000); return () => window.clearInterval(timer);
  }, [language, notificationState, reminders]);

  const switchLanguage = () => setLanguage((current) => current === "id" ? "en" : "id");
  const enableReminders = async () => { if (!("Notification" in window)) { setNotificationState("unsupported"); return; } const permission = await Notification.requestPermission(); setNotificationState(permission); if (permission === "granted") { setReminders(true); localStorage.setItem("ka-reminders", "true"); } };
  const disableReminders = () => { setReminders(false); localStorage.setItem("ka-reminders", "false"); };
  const install = async () => { if (!installPrompt) return; await installPrompt.prompt(); await installPrompt.userChoice; setInstallPrompt(null); };
  const dateChange = (value: string) => { setSelectedDate(value); setLimit(18); };

  return <main className="ka-page">
    <header className="ka-header"><a className="ka-brand" href="#top" aria-label="KA Festivals"><span className="ka-letter k">K</span><span className="ka-letter a">A</span><span className="festival-word">Festivals</span></a><nav><a href="#today">{t.navDaily}</a><a href="#calendar">{t.navCalendar}</a><a href="#guide">{t.navGuide}</a></nav><div className="header-tools"><button className="language-toggle" onClick={switchLanguage} aria-label={`${t.language}: ${language === "id" ? "English" : "Bahasa Indonesia"}`}><Languages size={15}/><span className={language === "id" ? "active" : ""}>ID</span><i/><span className={language === "en" ? "active" : ""}>EN</span></button>{(installPrompt || installed) && <button className="install-button" onClick={install} disabled={installed}>{installed ? <Check size={15}/> : <Download size={15}/>} {installed ? t.pwaInstalled : t.install}</button>}</div></header>

    <section className="ka-hero" id="top"><div className="hero-text"><span className="section-label"><Sparkles size={14}/> {t.dailyKicker}</span><h1>{t.heading}</h1><p>{t.intro}</p><div className="date-row"><label><span>{t.dateLabel}</span><input type="date" min="2026-01-01" max="2030-12-31" value={selectedDate} onChange={(event) => dateChange(event.target.value)}/></label><button onClick={() => dateChange(zonedDate("Asia/Jakarta"))} className="today-button"><CalendarCheck2 size={16}/>{t.today}</button></div></div><div className="hero-motif" aria-hidden="true"><div className="motif-sun"/><div className="motif-paper"><i/><i/><i/><i/></div><div className="motif-textile"/></div></section>

    <section className="daily-shell" id="today"><aside className="timezone-rail"><span className="section-label"><Clock3 size={14}/>{t.clockTitle}</span>{zoneList.map((item) => <Clock key={item.zone} label={item.label} zone={item.zone}/>)}</aside><div className="daily-content"><div className="daily-heading"><div><span className="section-label"><MapPin size={14}/>{isToday ? t.today : longDate(selectedDate, language)}</span><h2>{isToday ? longDate(selectedDate, language) : longDate(selectedDate, language)}</h2></div><div className="country-switch" aria-label={t.countryLabel}>{(["All","India","Indonesia"] as CountryFilter[]).map((entry) => <button key={entry} className={country === entry ? "selected" : ""} onClick={() => { setCountry(entry); setLimit(18); }}>{entry === "All" ? t.allCountries : entry === "India" ? t.india : t.indonesia}</button>)}</div></div>
      <div className={`today-card ${dayRecords.length ? "has-festival" : "quiet"}`}>{dayRecords.length ? <div className="today-list"><div className="today-lead"><span>{t.festivalToday}</span><h3>{dayRecords.length === 1 ? dayRecords[0].title[language] : `${dayRecords.length} ${language === "id" ? "perayaan berlangsung" : "celebrations are happening"}`}</h3></div>{dayRecords.map((entry) => <article key={entry.id} className="today-record"><div className={`record-mark ${kindColor[entry.kind]}`}>{entry.kind.slice(0,1)}</div><div><span className="record-meta">{entry.country} · {kindLabels[language][entry.kind]}</span><h4>{entry.title[language]}</h4><span className="casual-label">{t.casualNote}</span><p>{casualDescription(entry, language)}</p></div><span className={`status-stamp ${entry.status}`}>{statusLabel(entry.status, language)}</span></article>)}</div> : <div className="quiet-day"><div><span>{t.noFestival}</span><h3>{t.noFestivalDesc}</h3><p>{t.sourceNote}</p></div></div>}<CatCompanion hasFestival={dayRecords.length > 0} language={language}/></div>
      {country === "Indonesia" && year > 2026 && <div className="future-note"><Info size={16}/><span>{t.futureIndo}</span></div>}
    </div></section>

    <section className="calendar-section" id="calendar"><div className="calendar-intro"><span className="section-label"><Globe2 size={14}/>{t.yearKicker}</span><h2>{t.yearHeading}</h2><p>{t.yearNote}</p></div><div className="calendar-controls"><div className="year-tabs">{[2026,2027,2028,2029,2030].map((item) => <button key={item} className={item === year ? "active" : ""} onClick={() => dateChange(`${item}-01-01`)}>{item}</button>)}</div><label className="search-field"><Search size={17}/><input value={query} onChange={(event) => { setQuery(event.target.value); setLimit(18); }} placeholder={t.searchPlaceholder}/>{query && <button onClick={() => setQuery("")} aria-label="Clear search"><X size={15}/></button>}</label></div><div className="calendar-ledger">{calendarResults.slice(0,limit).map((entry) => <button className="calendar-entry" key={entry.id} onClick={() => dateChange(entry.date)}><time dateTime={entry.date}><strong>{entry.date.slice(8)}</strong><span>{new Intl.DateTimeFormat(language === "id" ? "id-ID" : "en-GB", {month:"short", timeZone:"UTC"}).format(new Date(`${entry.date}T12:00:00Z`))}</span></time><span className={`thread-dot ${kindColor[entry.kind]}`}/><span className="entry-copy"><span className="record-meta">{entry.country} · {kindLabels[language][entry.kind]}</span><strong>{entry.title[language]}</strong></span><span className={`status-stamp ${entry.status}`}>{statusLabel(entry.status, language)}</span></button>)}</div>{calendarResults.length > limit && <button className="load-more" onClick={() => setLimit((value) => value + 18)}>{t.loadMore} <ChevronDown size={16}/></button>}<p className="source-caution"><Info size={16}/>{t.sourceNote}</p></section>

    <section className="utility-grid" id="guide"><article className="notification-card"><span className="section-label"><Bell size={14}/>{t.notificationTitle}</span><h3>{reminders ? t.notificationReady : t.pwaReady}</h3><p>{notificationState === "denied" ? t.notificationBlocked : notificationState === "unsupported" ? t.notificationUnsupported : t.notificationCaveat}</p><button className={reminders ? "notification-toggle on" : "notification-toggle"} onClick={reminders ? disableReminders : enableReminders}>{reminders ? <BellOff size={16}/> : <Bell size={16}/>} {reminders ? t.disableNotifications : t.enableNotifications}</button></article><article className="guide-card"><span className="section-label"><Info size={14}/>{language === "id" ? "Cara membaca" : "How to read it"}</span><h3>{language === "id" ? "Tanggal punya kalender dan konteksnya sendiri." : "Dates belong to calendars and communities."}</h3><p>{t.sourceNote}</p></article></section>

    <footer className="ka-footer"><div className="ka-brand"><span className="ka-letter k">K</span><span className="ka-letter a">A</span><span className="festival-word">Festivals</span></div><p>{language === "id" ? "Kalender budaya India dan Indonesia, dirancang untuk rasa ingin tahu sehari-hari." : "An India and Indonesia cultural calendar, made for everyday curiosity."}</p><small>© 2026 KA Festivals · Static PWA</small></footer>
  </main>;
}
