/** KA Season Fieldbook: a warm, asymmetric reference route for broad local seasonal rhythms—not a live weather forecast or a replacement for local official guidance. */
import { ArrowLeft, ChevronRight, CloudRain, Compass, Leaf, MapPin, SunMedium } from "lucide-react";
import { Link } from "wouter";
import { useMemo, useState } from "react";
import { useLocale } from "@/contexts/LocaleContext";
import { solarPlaces, type SolarPlace } from "@/lib/solar";
import { usePageMeta } from "@/hooks/usePageMeta";

type SeasonCountry = "India" | "Indonesia";
const copy = { id: { back:"Kembali ke hari ini", eyebrow:"Peta musim", title:"Lima tempat, ritme musim yang berbeda.", intro:"Gunakan ini sebagai orientasi singkat sebelum memilih tanggal atau merencanakan perjalanan. Ini pola umum, bukan cuaca hari ini.", india:"India", indonesia:"Indonesia", choosePlace:"Pilih titik rujukan", chooseMonth:"Buka bulan", current:"Bulan yang dipilih", local:"Ritme setempat", typical:"Pola umum", note:"Catatan penting", source:"Sumber & batas model", disclaimer:"Mulai, puncak, dan akhir musim dapat berubah menurut zona dan tahun. Untuk kondisi berjalan, ikuti pembaruan IMD atau BMKG.", explore:"Lihat kalender bulan ini", monsoon:"Hujan / monsun", dry:"Lebih kering", transition:"Masa peralihan", cool:"Lebih sejuk", heat:"Lebih panas", metaTitle:"Peta musim India dan Indonesia", metaDescription:"Peta singkat ritme musim khas untuk Kolkata, Ranchi, Jakarta, Palangka Raya, dan Banjarmasin." }, en: { back:"Back to today", eyebrow:"Season fieldbook", title:"Five places, different seasonal rhythms.", intro:"Use this as a short orientation before choosing a date or planning a visit. It shows typical patterns, not today’s weather.", india:"India", indonesia:"Indonesia", choosePlace:"Choose a reference place", chooseMonth:"Open a month", current:"Selected month", local:"Local rhythm", typical:"Typical pattern", note:"Useful context", source:"Sources & model boundary", disclaimer:"Season starts, peaks, and endings can vary by zone and year. For current conditions, follow IMD or BMKG updates.", explore:"Open this month’s calendar", monsoon:"Rain / monsoon", dry:"Drier rhythm", transition:"Transition", cool:"Cooler rhythm", heat:"Warmer rhythm", metaTitle:"India and Indonesia season fieldbook", metaDescription:"A concise map of typical seasonal rhythms for Kolkata, Ranchi, Jakarta, Palangka Raya, and Banjarmasin." } };
const monthShort = { id:["Jan","Feb","Mar","Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des"], en:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"] };
const toneLabel = { id:{ rain:"Hujan / monsun", dry:"Lebih kering", transition:"Masa peralihan", cool:"Lebih sejuk", heat:"Lebih panas" }, en:{ rain:"Rain / monsoon", dry:"Drier rhythm", transition:"Transition", cool:"Cooler rhythm", heat:"Warmer rhythm" } };

function placeCountry(place: SolarPlace): SeasonCountry { return place.id === "kolkata" || place.id === "ranchi" ? "India" : "Indonesia"; }

export default function Seasons() {
  const { language } = useLocale(); const t = copy[language]; usePageMeta(t.metaTitle, t.metaDescription);
  const fromQuery = new URLSearchParams(window.location.search).get("place"); const requested = solarPlaces.find((place) => place.id === fromQuery); const [country, setCountry] = useState<SeasonCountry>(requested ? placeCountry(requested) : "India"); const [placeId, setPlaceId] = useState(requested?.id || "kolkata"); const [month, setMonth] = useState(() => new Date().getMonth() + 1);
  const places = useMemo(() => solarPlaces.filter((place) => placeCountry(place) === country), [country]); const place = places.find((item) => item.id === placeId) || places[0]; const band = place.seasonBands.find((item) => item.months.includes(month)) || place.seasonBands[0]; const calendarHref = `/explore?year=${new Date().getFullYear()}&month=${String(month).padStart(2,"0")}&country=${country}`;
  const changeCountry = (value: SeasonCountry) => { setCountry(value); setPlaceId(solarPlaces.find((place) => placeCountry(place) === value)?.id || "kolkata"); };
  return <section className="season-fieldbook" data-tone={band.tone}><Link href="/" className="back-link"><ArrowLeft size={16}/>{t.back}</Link><header className="season-fieldbook-head"><div><span className="eyebrow"><Compass size={14}/>{t.eyebrow}</span><h1>{t.title}</h1><p>{t.intro}</p></div><div className="season-compass" aria-hidden="true"><i/><i/><b>KA</b><span>{String(month).padStart(2,"0")}</span></div></header><div className="season-country-toggle" role="group" aria-label={language === "id" ? "Pilih negara" : "Choose country"}>{(["India","Indonesia"] as SeasonCountry[]).map((item) => <button key={item} className={country === item ? "active" : ""} aria-pressed={country === item} onClick={() => changeCountry(item)}>{item === "India" ? t.india : t.indonesia}</button>)}</div><div className="season-map-board"><aside className="season-atlas-art" aria-hidden="true"><span className="art-stamp">KA / SEASON</span><i className="art-sun"/><i className="art-rain"/><i className="art-leaf"/><b>{place.abbreviation}</b></aside><div className="season-reading"><div className="season-place-heading"><span><MapPin size={14}/>{t.choosePlace}</span><strong>{place.place[language]} · {place.region[language]}</strong></div><div className="season-place-tabs" role="tablist" aria-label={t.choosePlace}>{places.map((item) => <button key={item.id} role="tab" aria-selected={item.id === place.id} onClick={() => setPlaceId(item.id)}><small>{item.abbreviation}</small>{item.place[language]}</button>)}</div><div className="season-month-ruler" role="group" aria-label={t.chooseMonth}>{monthShort[language].map((label, index) => <button key={label} onClick={() => setMonth(index + 1)} aria-pressed={month === index + 1} className={`${band.months.includes(index + 1) ? "in-band" : ""} ${month === index + 1 ? "selected" : ""}`}><i/>{label}</button>)}</div><article className="season-now"><div><span>{t.current} · {monthShort[language][month - 1]}</span><h2>{band.title[language]}</h2><p>{band.note[language]}</p></div><div className="season-tone-mark"><SunMedium size={19}/><CloudRain size={19}/><Leaf size={19}/></div></article><div className="season-meta"><span>{t.typical}</span><strong>{toneLabel[language][band.tone]}</strong><p>{place.qualifier[language]}</p></div></div></div><section className="season-field-notes"><article><span className="eyebrow"><Leaf size={14}/>{t.local}</span><h2>{place.place[language]} · {band.period[language]}</h2><p>{band.note[language]}</p><Link href={calendarHref}>{t.explore}<ChevronRight size={16}/></Link></article><aside><span className="eyebrow"><Compass size={14}/>{t.source}</span><p>{t.disclaimer}</p><div><a href="https://mausam.imd.gov.in/imd_latest/contents/onset.php" target="_blank" rel="noreferrer">IMD <ChevronRight size={13}/></a><a href="https://iklim.bmkg.go.id/en/" target="_blank" rel="noreferrer">BMKG <ChevronRight size={13}/></a></div></aside></section></section>;
}
