/** Festival Arc: a responsive annual field-atlas that shows the year’s cultural rhythm before a visitor drills into a festival story. */
import { calendarRecords, kindColor, type Country, type FestivalRecord } from "@/data/calendar";
import { ArrowRight, CalendarRange, ChevronRight, Compass, MapPin, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { useMemo, useState } from "react";
import { useLocale } from "@/contexts/LocaleContext";
import { kindLabels, shortDate, statusLabels } from "@/lib/festival";
import { usePageMeta } from "@/hooks/usePageMeta";

type CountryFilter = "All" | Country;
const words = { id: { eyebrow: "Jalur tahun", title: "Satu tahun, banyak hari penting.", intro: "Pilih bulan untuk melihat perayaan yang tercatat. Lalu buka catatan singkatnya jika kamu ingin tahu lebih lanjut.", all: "Semua", india: "India", indonesia: "Indonesia", events: "perayaan", notes: "catatan", select: "Pilih bulan", upcoming: "Catatan awal 2027", upcomingIntro: "Tiga hari pertama yang dapat kamu buka dari jalur tahun ini.", open: "Buka catatan", official: "Tanggal India 2027 mengikuti daftar Pemerintah Pusat. Tanggal Islam dapat berubah setelah keputusan rukyat. Jadwal keagamaan Indonesia 2027 menunggu SKB 3 Menteri.", field: "Arti penanda", fixed: "Tanggal tetap", moving: "Tanggal bergerak", review: "Menunggu keputusan", route: "India · Nusantara", quarter: ["Awal tahun", "Masa ibadah", "Ruang bersama", "Akhir tahun"], metaTitle: "Jalur festival 2027", metaDescription: "Lihat catatan perayaan India dan Indonesia sepanjang 2027, dengan status tanggal yang jelas." }, en: { eyebrow: "Year route", title: "One year, many dates that matter.", intro: "Choose a month to see its listed celebrations. Open a short note whenever you want more context.", all: "All", india: "India", indonesia: "Indonesia", events: "celebrations", notes: "notes", select: "Choose a month", upcoming: "Early 2027 notes", upcomingIntro: "Three early dates you can open from this year’s route.", open: "Open note", official: "India’s 2027 dates follow the Central Government list. Islamic dates can change after local moon-sighting decisions. Indonesia’s 2027 religious schedule awaits the SKB 3 Menteri decree.", field: "What the markers mean", fixed: "Fixed date", moving: "Moving date", review: "Awaiting decision", route: "India · Nusantara", quarter: ["Opening months", "Prayer seasons", "Shared spaces", "Year-end"], metaTitle: "Festival route 2027", metaDescription: "See Indian and Indonesian celebration notes across 2027, with clear date-status context." } };

const monthName = (month: number, language: "id" | "en") => new Intl.DateTimeFormat(language === "id" ? "id-ID" : "en-GB", { month: "long", timeZone: "UTC" }).format(new Date(`2027-${String(month).padStart(2,"0")}-01T12:00:00Z`));

function TimelineRecord({ record, language }: { record: FestivalRecord; language: "id" | "en" }) { const t = words[language]; return <Link href={`/festival/${record.id}`} className="arc-record"><time><strong>{record.date.slice(8)}</strong><span>{new Intl.DateTimeFormat(language === "id" ? "id-ID" : "en-GB", { month: "short", timeZone:"UTC" }).format(new Date(`${record.date}T12:00:00Z`))}</span></time><span className={`arc-dot ${kindColor[record.kind]}`}/><div><span className="small-meta">{record.country} · {kindLabels[language][record.kind]}</span><h3>{record.title[language]}</h3></div><span className={`status-chip ${record.status}`}>{statusLabels[language][record.status]}</span><ChevronRight size={16}/></Link>; }

export default function Timeline() {
  const { language } = useLocale(); const t = words[language]; const [country, setCountry] = useState<CountryFilter>("All"); const [month, setMonth] = useState(1); usePageMeta(t.metaTitle, t.metaDescription);
  const records = useMemo(() => calendarRecords.filter((record) => record.date.startsWith("2027") && (country === "All" || record.country === country)).sort((a,b) => a.date.localeCompare(b.date)), [country]);
  const monthRecords = useMemo(() => records.filter((record) => Number(record.date.slice(5,7)) === month), [month, records]);
  const highlights = records.filter((record) => record.status !== "review").slice(0, 3);
  const monthCounts = Array.from({ length: 12 }, (_, index) => records.filter((record) => Number(record.date.slice(5,7)) === index + 1).length);
  const currentTitle = monthName(month, language);
  return <section className="timeline-page"><header className="timeline-heading"><span className="eyebrow"><CalendarRange size={14}/>{t.eyebrow}</span><h1>{t.title}</h1><p>{t.intro}</p><div className="arc-country-filter" role="group" aria-label={language === "id" ? "Pilih rute negara" : "Choose country route"}>{(["All","India","Indonesia"] as CountryFilter[]).map((item) => <button key={item} onClick={() => setCountry(item)} aria-pressed={country === item} className={country === item ? "active" : ""}>{item === "All" ? t.all : item === "India" ? t.india : t.indonesia}</button>)}</div></header>
    <section className="festival-arc" aria-label={t.select}><div className="arc-route"/><div className="arc-route-stamp" aria-hidden="true"><span>{t.route}</span><i/><b>KA</b></div><div className="arc-quarter-notes" aria-hidden="true">{t.quarter.map((note) => <span key={note}>{note}</span>)}</div>{monthCounts.map((count, index) => <button key={index} className={`arc-month ${month === index + 1 ? "active" : ""} ${count ? "has-events" : ""}`} onClick={() => setMonth(index + 1)}><span>{String(index + 1).padStart(2,"0")}</span><strong>{monthName(index + 1, language).slice(0,3)}</strong><i>{count}</i></button>)}</section>
    <section className="arc-focus"><div className="arc-focus-title"><span className="eyebrow"><Compass size={14}/>{t.field}</span><h2>{currentTitle}</h2><p>{monthRecords.length} {t.events}</p></div><div className="arc-focus-list">{monthRecords.length ? monthRecords.map((record) => <TimelineRecord key={record.id} record={record} language={language}/>) : <div className="arc-empty"><MapPin size={18}/><p>{language === "id" ? "Belum ada catatan pilihan untuk bulan ini." : "There are no selected notes for this month yet."}</p></div>}</div><div className="arc-material" aria-hidden="true"><span>2027</span><i/><i/><i/><b/></div></section>
    <section className="timeline-bottom"><article className="highlight-card"><span className="eyebrow"><Sparkles size={14}/>{t.upcoming}</span><p>{t.upcomingIntro}</p><div>{highlights.map((record) => <Link href={`/festival/${record.id}`} key={record.id}><time>{shortDate(record.date, language)}</time><strong>{record.title[language]}</strong><ArrowRight size={14}/></Link>)}</div></article><article className="timeline-guide"><span className="eyebrow"><Compass size={14}/>{t.field}</span><div className="marker-list"><span><i className="marker-fixed"/>{t.fixed}</span><span><i className="marker-moving"/>{t.moving}</span><span><i className="marker-review"/>{t.review}</span></div><p>{t.official}</p></article></section>
  </section>;
}
