/** Northwater shell: a compact compass identity, explicit locale context, glass mobile dock, and a non-astrological Pisces–Aquarius night ledger. */
import { ArrowUpRight, CalendarRange, Download, Globe2, Home, Map, Search, Sparkles } from "lucide-react";
import { Link, useLocation } from "wouter";
import { useEffect, useState } from "react";
import { useLocale } from "@/contexts/LocaleContext";

type InstallPromptEvent = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> };
const labels = { id: { home:"Hari ini", explore:"Indeks", timeline:"Tahunan", guide:"Panduan", install:"Pasang", installed:"Terpasang", language:"Bahasa", navigation:"Navigasi utama", footerKicker:"Rute langit", footerTitle:"Catatan langit untuk kalender bumi.", footerBody:"Pisces dan Aquarius hadir di sini sebagai penanda rute air dan musim—bukan ramalan.", footerLinks:"Jelajahi", source:"Tentang tanggal", constellation:"Konstelasi dekoratif" }, en: { home:"Today", explore:"Index", timeline:"Year", guide:"Guide", install:"Install", installed:"Installed", language:"Language", navigation:"Main navigation", footerKicker:"Sky routes", footerTitle:"Sky notes for an earthbound calendar.", footerBody:"Pisces and Aquarius appear here as water-and-season route markers—not predictions.", footerLinks:"Explore", source:"About dates", constellation:"Decorative constellations" } };

function Brand() { return <Link href="/" className="brand-new" aria-label="KA Festivals"><span className="brand-bloom" aria-hidden="true"><i/><i/><i/><i/><b>KA</b></span><span className="brand-lockup"><strong>KA</strong><em>Festivals</em><small>India · Indonesia</small></span></Link>; }

function ConstellationFooter() { const { language } = useLocale(); const t = labels[language]; return <footer className="northwater-footer"><div className="footer-intro"><Brand/><span className="eyebrow"><Sparkles size={14}/>{t.footerKicker}</span><h2>{t.footerTitle}</h2><p>{t.footerBody}</p><div className="footer-links"><Link href="/explore">{t.footerLinks}<ArrowUpRight size={14}/></Link><Link href="/guide">{t.source}<ArrowUpRight size={14}/></Link></div></div><div className="sky-ledger" aria-label={t.constellation}><div className="sky-grid"/><div className="constellation pisces"><span>♓ Pisces</span><svg viewBox="0 0 220 120" aria-hidden="true"><path d="M18 78L62 42L101 72L142 31L197 54"/><circle cx="18" cy="78" r="3"/><circle cx="62" cy="42" r="3"/><circle cx="101" cy="72" r="3"/><circle cx="142" cy="31" r="3"/><circle cx="197" cy="54" r="3"/></svg></div><div className="constellation aquarius"><span>♒ Aquarius</span><svg viewBox="0 0 230 130" aria-hidden="true"><path d="M19 41L70 59L114 30L155 83L211 60"/><circle cx="19" cy="41" r="3"/><circle cx="70" cy="59" r="3"/><circle cx="114" cy="30" r="3"/><circle cx="155" cy="83" r="3"/><circle cx="211" cy="60" r="3"/></svg></div><div className="sky-caption"><span>23H · −15°</span><i/><span>INDIA × INDONESIA</span></div></div></footer>; }

export default function SiteShell({ children }: { children: React.ReactNode }) {
  const { language, setLanguage } = useLocale(); const [location] = useLocation(); const [installPrompt, setInstallPrompt] = useState<InstallPromptEvent | null>(null); const [installed, setInstalled] = useState(false); const t = labels[language];
  useEffect(() => { if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => undefined); const beforeInstall = (event: Event) => { event.preventDefault(); setInstallPrompt(event as InstallPromptEvent); }; const installedHandler = () => { setInstalled(true); setInstallPrompt(null); }; window.addEventListener("beforeinstallprompt", beforeInstall); window.addEventListener("appinstalled", installedHandler); return () => { window.removeEventListener("beforeinstallprompt", beforeInstall); window.removeEventListener("appinstalled", installedHandler); }; }, []);
  const install = async () => { if (!installPrompt) return; await installPrompt.prompt(); await installPrompt.userChoice; setInstallPrompt(null); };
  const nav = [{ href:"/", icon:Home, label:t.home }, { href:"/explore", icon:Search, label:t.explore }, { href:"/timeline", icon:CalendarRange, label:t.timeline }, { href:"/guide", icon:Map, label:t.guide }];
  return <div className="app-frame"><a className="skip-link" href="#main-content">{language === "id" ? "Lewati ke isi" : "Skip to content"}</a><header className="site-header-new"><Brand/><nav className="desktop-nav" aria-label={t.navigation}>{nav.map(({ href,label }) => <Link key={href} href={href} className={location === href ? "active" : ""}>{label}</Link>)}</nav><div className="header-actions"><div className="language-control" role="group" aria-label={t.language}><span className="language-icon" aria-hidden="true"><Globe2 size={14}/></span><button type="button" onClick={() => setLanguage("id")} className={language === "id" ? "active" : ""} aria-pressed={language === "id"}>ID</button><button type="button" onClick={() => setLanguage("en")} className={language === "en" ? "active" : ""} aria-pressed={language === "en"}>EN</button></div>{(installPrompt || installed) && <button onClick={install} disabled={installed} className="install-tile"><Download size={16}/><span>{installed ? t.installed : t.install}</span></button>}</div></header><main id="main-content">{children}</main><ConstellationFooter/><nav className="mobile-dock" aria-label={t.navigation}><i className="dock-glint" aria-hidden="true"/>{nav.map(({ href, icon:Icon, label }) => <Link key={href} href={href} className={location === href ? "active" : ""}><Icon size={18}/><span>{label}</span></Link>)}</nav></div>;
}
