/** Solar Ledger: a real-time local clock with approximate astronomical daylight markers and a transparently qualified seasonal rhythm. */
import { ChevronRight, Clock3, Info, Moon, Sunrise, Sunset, SunMedium } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocale } from "@/contexts/LocaleContext";
import { formatLiveTime, formatSolarTime, getSolarSnapshot, solarPlaces } from "@/lib/solar";

const words = { id:{ eyebrow:"Solar Ledger", title:"Waktu berjalan. Langit berubah.", body:"Detik, cahaya, dan ritme musim untuk lima titik rujukan.", select:"Pilih lokasi", sunrise:"Terbit", sunset:"Terbenam", approximate:"waktu perkiraan", typical:"Ritme umum", source:"Tentang dasar musim", night:"Malam", dawn:"Fajar", day:"Siang", dusk:"Senja", details:"Lihat musim", notice:"Jam matahari dihitung dari lokasi dan tanggal; bukan cuaca saat ini." }, en:{ eyebrow:"Solar Ledger", title:"Time moves. The sky changes.", body:"Seconds, daylight, and seasonal rhythm for five reference points.", select:"Choose a place", sunrise:"Sunrise", sunset:"Sunset", approximate:"approximate time", typical:"Typical rhythm", source:"About the seasonal basis", night:"Night", dawn:"Dawn", day:"Daylight", dusk:"Dusk", details:"View season", notice:"Solar time is calculated from place and date; it is not current weather." } };

export default function SolarLedger({ placeId, onPlaceChange }: { placeId: string; onPlaceChange: (placeId: string) => void }) {
  const { language } = useLocale(); const t = words[language]; const [now, setNow] = useState(() => new Date()); const place = useMemo(() => solarPlaces.find((item) => item.id === placeId) || solarPlaces[0], [placeId]); const snapshot = getSolarSnapshot(now, place); const PhaseIcon = snapshot.phase === "night" ? Moon : snapshot.phase === "dawn" ? Sunrise : snapshot.phase === "dusk" ? Sunset : SunMedium;
  useEffect(() => { let interval = 0; const begin = () => { setNow(new Date()); interval = window.setInterval(() => setNow(new Date()), 1000); }; const timeout = window.setTimeout(begin, 1000 - (Date.now() % 1000)); return () => { window.clearTimeout(timeout); window.clearInterval(interval); }; }, []);
  const monthShort = new Intl.DateTimeFormat(language === "id" ? "id-ID" : "en-GB", { month:"short", timeZone:place.zone }).format(new Date(now));
  return <section className="solar-ledger" data-phase={snapshot.phase} aria-labelledby="solar-ledger-title"><header className="solar-ledger-head"><div><span className="eyebrow"><Clock3 size={14}/>{t.eyebrow}</span><h2 id="solar-ledger-title">{t.title}</h2><p>{t.body}</p></div><span className="solar-live-tag"><i/>{t[snapshot.phase]}</span></header><div className="solar-place-tabs" role="tablist" aria-label={t.select}>{solarPlaces.map((item) => <button key={item.id} role="tab" aria-selected={place.id === item.id} onClick={() => onPlaceChange(item.id)}><span>{item.place[language]}</span><small>{item.abbreviation}</small></button>)}</div><div className="solar-instrument"><div className="solar-time"><span>{place.place[language]} · {place.region[language]}</span><time dateTime={now.toISOString()}>{formatLiveTime(now, place.zone)}</time><small>{place.abbreviation} · {monthShort}</small></div><div className="solar-arc" style={{ "--sun-position": `${snapshot.daylightProgress * 100}%` } as React.CSSProperties} aria-label={`${t.sunrise} ${formatSolarTime(snapshot.sunrise, place.zone)}, ${t.sunset} ${formatSolarTime(snapshot.sunset, place.zone)}`}><div className="solar-horizon"><i className="solar-sun"/><b/><b/><b/></div><div className="solar-mark sunrise"><Sunrise size={14}/><span>{t.sunrise}</span><strong>{formatSolarTime(snapshot.sunrise, place.zone)}</strong></div><div className="solar-mark sunset"><Sunset size={14}/><span>{t.sunset}</span><strong>{formatSolarTime(snapshot.sunset, place.zone)}</strong></div><PhaseIcon className="solar-phase-icon" size={16} aria-hidden="true"/></div><div className={`solar-season ${snapshot.season.tone}`}><div><span>{t.typical} · {snapshot.season.period[language]}</span><h3>{snapshot.season.title[language]}</h3><p>{snapshot.season.note[language]}</p></div><div className="season-month-dots" aria-hidden="true">{Array.from({ length:12 }, (_, index) => <i key={index} className={snapshot.season.months.includes(index + 1) ? "active" : ""}>{String(index + 1).padStart(2,"0")}</i>)}</div><small><Info size={13}/>{place.qualifier[language]}</small></div></div><footer><span><Info size={13}/>{t.notice}</span><a href="/guide">{t.source}<ChevronRight size={14}/></a></footer></section>;
}
